# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 860)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loginFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.loginFrame.setGeometry(QtCore.QRect(600, 110, 411, 581))
        self.loginFrame.setStyleSheet("#loginFrame {\n"
"    background-color: rgba(255,248,254, 1); /* Màu nền trắng, trong suốt 90% */\n"
"    border-radius: 15px; /* Bo góc */\n"
"    padding: 20px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    color: black;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-size: 14px;\n"
"background-color: white;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: #fff8fe;\n"
"}\n"
"#loginButton {\n"
"    background-color: #c1ffc9;\n"
"    color: #ff2c5d;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"#loginButton:hover {\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"#titleLabel {\n"
"    font-size: 25px;\n"
"    font-weight: bold;\n"
"    color: #ff547c;\n"
"    text-align: center;\n"
"}\n"
"\n"
"#usernameLabel {\n"
"    background-color: #fff6fb;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}\n"
"\n"
"#passwordLabel {\n"
"    background-color: #fff6fb;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}\n"
" #label3 { \n"
"    background-color: #fff6fb;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}\n"
"\n"
"#label3_2 {\n"
"    background-color: #fff6fb;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}    #label3_3 { \n"
"    background-color: #fff6fb;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}  \n"
"#label3_4 { \n"
"    background-color: #fff6fb;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}\n"
"QRadioButton{\n"
"    color: black; \n"
"    border: 1px solid #ccc;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    font-size: 14px;\n"
"background-color: white;\n"
"}\n"
"QRadioButton:hover { \n"
"    background-color: #fff8fe;\n"
"}")
        self.loginFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.loginFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.loginFrame.setObjectName("loginFrame")
        self.titleLabel = QtWidgets.QLabel(parent=self.loginFrame)
        self.titleLabel.setGeometry(QtCore.QRect(120, 30, 171, 21))
        self.titleLabel.setObjectName("titleLabel")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.lineEdit.setGeometry(QtCore.QRect(30, 100, 341, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 160, 341, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.loginButton = QtWidgets.QPushButton(parent=self.loginFrame)
        self.loginButton.setGeometry(QtCore.QRect(120, 490, 151, 41))
        self.loginButton.setObjectName("loginButton")
        self.usernameLabel = QtWidgets.QLabel(parent=self.loginFrame)
        self.usernameLabel.setGeometry(QtCore.QRect(40, 90, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setToolTipDuration(16)
        self.usernameLabel.setObjectName("usernameLabel")
        self.passwordLabel = QtWidgets.QLabel(parent=self.loginFrame)
        self.passwordLabel.setGeometry(QtCore.QRect(40, 150, 61, 16))
        self.passwordLabel.setObjectName("passwordLabel")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 220, 341, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label3 = QtWidgets.QLabel(parent=self.loginFrame)
        self.label3.setGeometry(QtCore.QRect(40, 210, 41, 16))
        self.label3.setObjectName("label3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.lineEdit_4.setGeometry(QtCore.QRect(30, 280, 341, 41))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.loginFrame)
        self.lineEdit_5.setGeometry(QtCore.QRect(30, 350, 341, 41))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label3_2 = QtWidgets.QLabel(parent=self.loginFrame)
        self.label3_2.setGeometry(QtCore.QRect(40, 270, 41, 16))
        self.label3_2.setObjectName("label3_2")
        self.label3_3 = QtWidgets.QLabel(parent=self.loginFrame)
        self.label3_3.setGeometry(QtCore.QRect(40, 340, 81, 16))
        self.label3_3.setObjectName("label3_3")
        self.radioButton = QtWidgets.QRadioButton(parent=self.loginFrame)
        self.radioButton.setGeometry(QtCore.QRect(240, 440, 61, 31))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.loginFrame)
        self.radioButton_2.setGeometry(QtCore.QRect(90, 440, 71, 31))
        self.radioButton_2.setObjectName("radioButton_2")
        self.label3_4 = QtWidgets.QLabel(parent=self.loginFrame)
        self.label3_4.setGeometry(QtCore.QRect(40, 410, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label3_4.setFont(font)
        self.label3_4.setObjectName("label3_4")
        self.backgroundLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.backgroundLabel.setGeometry(QtCore.QRect(0, 0, 1600, 860))
        self.backgroundLabel.setText("")
        self.backgroundLabel.setPixmap(QtGui.QPixmap(r"C:\Users\THUYHANG-PC\Documents\BTL Lập trình Python\image\menu/3.jpg"))
        self.backgroundLabel.setScaledContents(True)
        self.backgroundLabel.setObjectName("backgroundLabel")
        self.backgroundLabel.raise_()
        self.loginFrame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 979, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleLabel.setText(_translate("MainWindow", "Coffee house"))
        self.loginButton.setText(_translate("MainWindow", "Đăng ký"))
        self.usernameLabel.setText(_translate("MainWindow", "Tên đăng nhập"))
        self.passwordLabel.setText(_translate("MainWindow", "Mật khẩu"))
        self.label3.setText(_translate("MainWindow", "Họ tên"))
        self.label3_2.setText(_translate("MainWindow", "Email"))
        self.label3_3.setText(_translate("MainWindow", "Số điện thoại"))
        self.radioButton.setText(_translate("MainWindow", "Nữ"))
        self.radioButton_2.setText(_translate("MainWindow", "Nam"))
        self.label3_4.setText(_translate("MainWindow", "Giới tính:"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
